services:
  db:
    image: postgres
    restart: always
    container_name: gopher-db
    environment:
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - data_db:/var/lib/postgresql/data 

volumes:
  data_db:
